/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e9e7",
        "outline-variant": "#c0c9bb",
        "primary-fixed-dim": "#88d982",
        "surface-container-low": "#f2f4f2",
        "inverse-primary": "#88d982",
        "surface-container": "#eceeec",
        "secondary": "#4c616c",
        "on-primary-container": "#86d881",
        "background": "#f8faf8",
        "tertiary": "#523327",
        "tertiary-fixed-dim": "#ebbcac",
        "surface-tint": "#1b6d24",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dad9",
        "secondary-container": "#cfe6f2",
        "secondary-fixed-dim": "#b4cad6",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary": "#00450d",
        "on-primary-fixed-variant": "#005312",
        "on-surface-variant": "#41493e",
        "surface": "#f8faf8",
        "on-tertiary-fixed-variant": "#603f33",
        "on-secondary": "#ffffff",
        "primary-fixed": "#a3f69c",
        "surface-container-highest": "#e1e3e1",
        "on-surface": "#191c1b",
        "outline": "#717a6d",
        "on-secondary-fixed-variant": "#354a53",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#e9baaa",
        "error-container": "#ffdad6",
        "tertiary-container": "#6c493d",
        "inverse-surface": "#2e3130",
        "tertiary-fixed": "#ffdbcf",
        "on-tertiary-fixed": "#2e150b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#526772",
        "on-secondary-fixed": "#071e27",
        "on-primary-fixed": "#002204",
        "surface-bright": "#f8faf8",
        "surface-variant": "#e1e3e1",
        "on-error": "#ffffff",
        "primary-container": "#065f18",
        "on-background": "#191c1b",
        "inverse-on-surface": "#eff1ef",
        "secondary-fixed": "#cfe6f2"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
};
